In [2]:
  import numpy as np

In [3]:
l1=[1,2,3,4]

In [5]:
n1=np.array(l1)

In [22]:
n1.shape

(4,)

In [7]:
type(n1)

numpy.ndarray

In [10]:
n2=np.array([[1,2,3,4],[7,9,6,1]])

In [24]:
n2.shape=(4,2)
n2

array([[1, 2],
       [3, 4],
       [7, 9],
       [6, 1]])

In [12]:
n3=np.zeros((7,7))

In [13]:
n3

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
n4=np.zeros((100,100))
n4

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
n5=np.full((1,9),10)
n5

array([[10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [18]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
n7=np.arange(10,30,3)
n7

array([10, 13, 16, 19, 22, 25, 28])